default_settings:
  trainer_type: ppo #Вказує, що використовується алгоритм Proximal Policy Optimization для тренування.
  hyperparameters:
    batch_size: 16 #Розмір партії даних, що обробляється за один раз
    buffer_size: 120 #Розмір буфера, де зберігаються досвіди до використання
    learning_rate: 0.0003 #Швидкість навчання.
    beta: 0.005 #Коефіцієнт регуляризації для зниження розміру політики.
    epsilon: 0.2 #Коефіцієнт використовується для обмеження відхилень у політиці між ітераціями.
    lambd: 0.99 #Параметр в алгоритмі GAE (Generalized Advantage Estimation).
    num_epoch: 3 #Кількість епох для використання даних перед їх видаленням
    learning_rate_schedule: constant #Політика зміни швидкості навчання (тут вона стала)
  network_settings:
    normalize: true #Чи нормалізувати вхідні дані
    hidden_units: 256 #Кількість одиниць у прихованих шарах.
    num_layers: 4 #Кількість прихованих шарів.
    vis_encode_type: match3 #Тип кодування, специфічний для задач match3.
  reward_signals:
    extrinsic:
      gamma: 0.99 #Коефіцієнт дисконтування, що використовується для розрахунку майбутніх винагород.
      strength: 1.0 #Сила екстризичного сигналу винагороди.
  keep_checkpoints: 5 #Кількість контрольних точок моделі для зберігання.
  max_steps: 5000000 #Максимальна кількість кроків тренування
  time_horizon: 128 #Кількість кроків у середовищі, що збираються перед опрацюванням
  summary_freq: 10000 #Частота, з якою збираються та записуються статистичні дані
  threaded: true #Чи використовувати багатопоточність при тренуванні

behaviors:
  Match3Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16
      buffer_size: 120
    network_settings:
      hidden_units: 4
      num_layers: 1
    max_steps: 5000000 #Максимальна кількість кроків тренування
    summary_freq: 100
    threaded: true #Чи використовувати багатопоточність при тренуванні